//! `hex::workers` — the registry of typed Rust workers hosted by the harness.
//!
//! Each submodule defines one worker via `pub fn worker() -> Worker`. The
//! `registry()` function returns them all; the harness runtime registers
//! each worker's `(TriggerSpec, Handler)` pairs with iii at startup.

pub mod e2e;

// Generated by build.rs: per *.worker.rs `#[path] pub mod <ident>;` +
// `module_registry()` + `module_paths()`.
pub mod hex_modules {
    include!(concat!(env!("OUT_DIR"), "/hex_modules.rs"));
}

use crate::worker::Worker;

/// Return all workers hosted by the hex harness.
///
/// The test-only `hex-e2e` worker is appended ONLY when `HEX_HARNESS_E2E=1`
/// (set by the harness-e2e container) — it never registers in a real deployment.
pub fn registry() -> Vec<Worker> {
    let mut workers = hex_modules::module_registry();
    if std::env::var("HEX_HARNESS_E2E").as_deref() == Ok("1") {
        workers.push(e2e::worker());
    }
    let mut seen = std::collections::BTreeSet::new();
    for w in &workers {
        assert!(
            seen.insert(w.name.clone()),
            "hex registry: duplicate worker name '{}'",
            w.name
        );
    }
    workers
}

#[cfg(test)]
mod tests {
    use super::hex_modules;
    use super::*;
    use crate::worker::TriggerSpec;

    fn cron_exprs(w: &Worker) -> Vec<String> {
        w.handlers
            .iter()
            .filter_map(|(_name, spec, _)| match spec {
                TriggerSpec::Cron { expression } => Some(expression.clone()),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn registry_includes_memory_maintenance_and_backup() {
        let reg = registry();
        let names: Vec<&str> = reg.iter().map(|w| w.name.as_str()).collect();
        assert!(names.contains(&"hex-memory-maintenance"));
        assert!(names.contains(&"hex-backup"));
    }

    #[test]
    fn memory_maintenance_cron_matches_yaml() {
        let reg = registry();
        let mm = reg
            .iter()
            .find(|w| w.name == "hex-memory-maintenance")
            .expect("hex-memory-maintenance present");
        let exprs = cron_exprs(mm);
        assert!(exprs
            .iter()
            .any(|e| e == hex_modules::memory_maintenance::CRON_INDEX));
        assert!(exprs
            .iter()
            .any(|e| e == hex_modules::memory_maintenance::CRON_CONSOLIDATE_FULL));
    }

    #[test]
    fn memory_maintenance_registers_quick_and_parse_transcripts_crons() {
        // Phase A additive redesign: the worker must also register cron jobs
        // for `hex memory consolidate quick` and `hex memory parse-transcripts`,
        // both on a 15-minute cadence.
        let reg = registry();
        let mm = reg
            .iter()
            .find(|w| w.name == "hex-memory-maintenance")
            .expect("hex-memory-maintenance present");
        let exprs = cron_exprs(mm);

        // The quick-consolidate cron must be registered with a 15-min cadence.
        assert!(
            exprs
                .iter()
                .any(|e| e == hex_modules::memory_maintenance::CRON_CONSOLIDATE_QUICK),
            "expected CRON_CONSOLIDATE_QUICK to be registered, got crons: {:?}",
            exprs
        );
        assert_eq!(
            hex_modules::memory_maintenance::CRON_CONSOLIDATE_QUICK,
            "0 5,20,35,50 * * * * *",
            "quick-consolidate must run 4x/hour OFFSET from :00 — a quick tick \
             on the :00 boundary lock-skipped the 03:00:00Z full run (2026-06-10)"
        );
        assert_eq!(
            hex_modules::memory_maintenance::ARGV_CONSOLIDATE_QUICK,
            &["hex", "memory", "consolidate", "quick"],
        );

        // The parse-transcripts cron must be registered with a 15-min cadence.
        assert!(
            exprs
                .iter()
                .any(|e| e == hex_modules::memory_maintenance::CRON_PARSE_TRANSCRIPTS),
            "expected CRON_PARSE_TRANSCRIPTS to be registered, got crons: {:?}",
            exprs
        );
        assert_eq!(
            hex_modules::memory_maintenance::CRON_PARSE_TRANSCRIPTS,
            "0 */15 * * * * *",
            "parse-transcripts must run every 15 minutes"
        );
        assert_eq!(
            hex_modules::memory_maintenance::ARGV_PARSE_TRANSCRIPTS,
            &["hex", "memory", "parse-transcripts"],
        );
    }

    #[test]
    fn backup_is_cron_worker() {
        let reg = registry();
        let bk = reg
            .iter()
            .find(|w| w.name == "hex-backup")
            .expect("hex-backup present");
        assert!(!cron_exprs(bk).is_empty());
    }

    #[test]
    fn backup_offsite_registered_at_0430() {
        let reg = registry();
        let off = reg
            .iter()
            .find(|w| w.name == "hex-backup-offsite")
            .expect("hex-backup-offsite present");
        let exprs = cron_exprs(off);
        assert!(
            exprs
                .iter()
                .any(|e| e == hex_modules::backup_offsite::CRON_OFFSITE),
            "offsite worker must register its 04:30 cron, got: {:?}",
            exprs
        );
        assert_eq!(
            hex_modules::backup_offsite::ARGV_OFFSITE,
            &["hex", "backup", "offsite"],
        );
    }

    #[test]
    fn applier_worker_registers_daily_run_and_watch_crons() {
        let reg = registry();
        let ap = reg
            .iter()
            .find(|w| w.name == "hex-applier")
            .expect("hex-applier present");
        let exprs = cron_exprs(ap);
        assert!(
            exprs.iter().any(|e| e == hex_modules::applier::CRON_RUN),
            "hex-applier must register its 05:00 UTC run cron, got: {:?}",
            exprs
        );
        assert!(
            exprs.iter().any(|e| e == hex_modules::applier::CRON_WATCH),
            "hex-applier must register its 05:10 UTC watch cron, got: {:?}",
            exprs
        );
        assert_eq!(hex_modules::applier::ARGV_RUN, &["hex", "apply", "run"]);
        assert_eq!(hex_modules::applier::ARGV_WATCH, &["hex", "apply", "watch"]);
    }

    /// Moved from the removed tests/module_discovery.rs: module discovery
    /// against the real generated registry, checked by source path shape
    /// rather than just by name.
    #[test]
    fn core_modules_are_discovered_with_source_paths() {
        let paths = hex_modules::module_paths();
        // memory_maintenance + backup were migrated into src/modules/ and must show up.
        let names: Vec<&str> = paths.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"hex-memory-maintenance"), "got: {names:?}");
        assert!(names.contains(&"hex-backup"), "got: {names:?}");
        // Their source paths point at *.worker.rs under src/modules/.
        for (name, path) in &paths {
            if name == "hex-memory-maintenance" || name == "hex-backup" {
                assert!(
                    path.contains("/src/modules/") && path.ends_with(".worker.rs"),
                    "{name} source should be a src/modules/*.worker.rs file, got {path}"
                );
            }
        }
    }

    #[test]
    fn registry_includes_generated_module_registry() {
        // The generated module_registry() is a source of workers in registry().
        let gen = hex_modules::module_registry();
        let reg = registry();
        for w in &gen {
            assert!(
                reg.iter().any(|r| r.name == w.name),
                "registry() must include generated module '{}'",
                w.name
            );
        }
    }

    #[test]
    fn registry_names_are_unique() {
        let reg = registry();
        let mut seen = std::collections::BTreeSet::new();
        for w in &reg {
            assert!(
                seen.insert(w.name.clone()),
                "duplicate worker name: {}",
                w.name
            );
        }
    }
}
